-- SQL Dump of db_scambio.mdb
-- generated by MDB Viewer 2.2.5
-- optimized for MySQL

SET NAMES 'UTF8';

INSERT INTO Agenti values (1,'MONACO FABIO','','Via della Resistenza n. 20/A','Scafati','SA','84018',NULL,NULL,NULL,NULL,NULL,NULL,'MNCFBA67H16L259I','02825431212','IT02825431212','081 8561688','081 8508585','081 8564262','','','338 4071790',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Italy',NULL,'info@dercam.it',NULL,'www.dercam.it','EURO',NULL,35,'001');

-- The free trial of MDB ACCDB Viewer exports only half of the records in each table.
INSERT INTO `Agenti`(`id tabella`,`Nominativo`,`seconda_riga`,`indirizzo`,`citta`,`pr`,`cap`,`Ragione2`,`seconda2`,`magazzino`,`citta2`,`pr2`,`cap2`,`codfis`,`piva`,`pivaCEE`,`tel`,`tel2`,`fax`,`fax2`,`telcont`,`Contatto`,`banca`,`baabi`,`bacab`,`baconto`,`banca2`,`baabi2`,`bacab2`,`baconto2`,`swift1`,`swift2`,`corriere`,`cotel`,`coindi`,`cocitta`,`coabb`,`ModPagamento`,`TipoPagamento`,`nazione`,`nazione2`,`email`,`Note`,`WWW`,`Valuta`,`Settore`,`Provv%`,`CodiceUnivoco`)
VALUES(1,'MONACO FABIO','','Via della Resistenza n. 20/A','Scafati','SA','84018',NULL,NULL,NULL,NULL,NULL,NULL,'MNCFBA67H16L259I','02825431212','IT02825431212','081 8561688','081 8508585','081 8564262','','','338 4071790',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Italy',NULL,'info@dercam.it',NULL,'www.dercam.it','EURO',NULL,35,'001');


